---
- name: Install Logstash.
  hosts: all
  become: true
  vars:
    java_ubuntu: openjdk-11-jdk
    java_redhat: java-1.8.0-openjdk
    logstash_version: '7.x'
    logstash_listen_port_beats: 5044
    logstash_ssl_dir: /etc/pki/logstash
    logstash_ssl_certificate_file: ""
    logstash_ssl_key_file: ""
    logstash_local_syslog_path: /var/log/syslog
    logstash_elasticsearch_host: http://localhost:9202

  handlers:
    - import_tasks: handlers/main.yml

  tasks:
    # Setup/install tasks.
    # - include_tasks: setup-RedHat.yml
    - name: Ensure Java is installed on RedHat.
      yum:
        name: "{{ java_redhat }}"
        state: present
      when: ansible_os_family == 'RedHat'

    # #- include_tasks: setup-Debian.yml
    # - name: Ensure 'man' directory exists.
    #   file:
    #     path: /usr/share/man/man1
    #     state: directory
    #     mode: 0755
    #     recurse: true
    #   when:
    #     - ansible_distribution == 'Ubuntu'
    #     - ansible_distribution_major_version | int >= 18

    - name: Ensure Java is installed on Ubuntu.
      apt:
        name: "{{ java_ubuntu }}"
        state: present
      when: ansible_os_family == 'Debian'

#    - name: Include OS Specific setup tasks
#      include: setup-{{ ansible_os_family }}.yml
    - name: Add Elasticsearch GPG key.
      rpm_key:
        key: https://artifacts.elastic.co/GPG-KEY-elasticsearch
        state: present
      when: ansible_os_family == "RedHat"

    - name: Ensure required dependencies are installed.
      apt:
        name:
          - apt-transport-https
          - gnupg2
        state: present
      when: ansible_os_family == "Debian"

    - name: Add Elasticsearch apt key.
      apt_key:
        url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
        state: present
      when: ansible_os_family == "Debian"

    - name: Add Logstash repository.
      apt_repository:
        repo: 'deb https://artifacts.elastic.co/packages/{{ logstash_version }}/apt stable main'
        state: present
        update_cache: true
      when: ansible_os_family == "Debian"

    - name: Install Logstash.
      apt:
        name: logstash
        state: present
      when: ansible_os_family == "Debian"

    - name: Add Logstash user to adm group (Debian).
      user:
        name: logstash
        group: logstash
        groups: adm
      notify: restart logstash
      when: ansible_os_family == "Debian"

    - name: Make sure handlers are flushed immediately.
      meta: flush_handlers

    - name: Add Logstash repository.
      template:
        src: template/logstash.repo.j2
        dest: /etc/yum.repos.d/logstash.repo
        mode: 0644
      when: ansible_os_family == "RedHat"

    - name: Install Logstash on {{ ansible_os_family }}.
      yum:
        name: logstash
        state: present
      when: ansible_os_family == "RedHat"

#- include: config.yml
    - name: Configure Logstash files.
      template:
        src: "template/{{ item }}.j2"
        dest: "/etc/logstash/conf.d/{{ item }}"
        owner: root
        group: root
        mode: 0644
      loop:
        - 01-beats-input.conf
        - 02-local-syslog-input.conf
        - 30-elastic-output.conf
      notify: restart logstash

    - name: Make sure handlers are flushed immediately.
      meta: flush_handlers

#- include: plugins.yml
    - name: Ensure Logstash is started and enabled on boot.
      service:
        name: logstash
        state: started
        enabled: true
